name: CI
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [4, 6, 8, 10, 12, 14, 16, 18]
        os: [ubuntu-latest]
        include:
          - node: 14
            os: macos-latest
            CPPFLAGS: "-I/usr/local/opt/openssl/include"
            LDFLAGS: "-L/usr/local/opt/openssl/lib"
          - node: 16
            os: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node - ${{ matrix.node }} in ${{ runner.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}
      - name: Setup docker containers
        if: runner.os == 'Linux'
        run: ./run_docker.sh
      - name: Install Windows packages
        if: runner.os == 'Windows'
        run: ./win_install.ps1
      - name: Fix node-gyp on node 8
        if: ${{ matrix.node == '8' }}
        run: npm explore npm/node_modules/npm-lifecycle -g -- npm install node-gyp@6.1.0
      - name: Install Dependencies
        run: |
          npm install
      - name: Test On Node ${{ matrix.node }} in ${{ runner.os }}

        run: |
          make lint
          make test
          make check
