# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish node-rdkafka

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        version: [8, 10, 12, 14, 15, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: cache
        uses: actions/cache@v3.0.11
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}-${{ hashFiles('npm-shrinkwrap.json') }}
      - run: npm ci
      - run: npm test
        name: test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: cache
        uses: actions/cache@v3.0.11
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}-${{ hashFiles('npm-shrinkwrap.json') }}
      - run: npm ci
      - run: npm run configure --if-present
      - run: npm run build --if-present
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
